name: Deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://cvaugh.dev/deploy-git.php'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"project": "acm", "action": "deploy", "commit": "${{ github.sha }}", "key": "${{ secrets.DEPLOY_KEY }}"}'
